Failed running run_frozen_graph_ssdmob.py
Failed running ssd-mobilenet  run_frozen_graph_ssdmob.py in python3 because of the python3 Syntax
Here is the error message
```
  File "/workspace/intelai_models/inference/int8/run_frozen_graph_ssdmob.py", line 186
    print tensor.shape
               ^
SyntaxError: Missing parentheses in call to 'print'

```
Change the Syntax to support python3